version: '3.8'

services:
  app:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "${APP_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "npm install && npm start"

  db:
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_MAX_CONNECTIONS=1000
      - SERVICE_TAGS=${NODE_ENV}
      - SERVICE_NAME=mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 1000000000

volumes:
  mariadb_data: 